[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/services"
  to = "/consultancy"
  status = 301

[[redirects]]
  from = "/services.html"
  to = "/consultancy"
  status = 301

[[redirects]]
  from = "/join"
  to = "/portugal#join"
  status = 301

[[redirects]]
  from = "/join.html"
  to = "/portugal#join"
  status = 301

[[headers]]
  for = "/admin/*"
    [headers.values]
    X-Robots-Tag = "noindex"

# Enable Netlify Identity
[dev]
  framework = "#static"
